### ISSUE TITLE
preg_match(): JIT compilation failed: no more memory

### ISSUE THREAD

**Issue by seeyouleta** [giuscris/formwork#24]
I tried Formwork on macOS High Sierra with MAMP (5.3) and I got this error:

`[18-Mar-2019 12:32:53 UTC] PHP Fatal error:  Uncaught ErrorException: preg_match(): JIT compilation failed: no more memory in /Applications/MAMP/htdocs/formwork/Utils/Visitor.php:47`

**Comment by giuscris** [comment]
Are you using PHP 7.3? It seems it's a known PHP 7.3 [bug](https://bugs.php.net/bug.php?id=77260). Setting `pcre.jit=0` in PHP configuration file should avoid that.

**Comment by seeyouleta** [comment]
I’ve found a solution by switching from PHP 7.3 to 7.2.14, now everything works fine.
